#!/bin/bash

cd `dirname $0`
mkdir -p proprietary/gapps

adb pull /system/app/CarHomeGoogle.apk proprietary/gapps
adb pull /system/app/CarHomeLauncher.apk proprietary/gapps
adb pull /system/app/Facebook.apk proprietary/gapps
adb pull /system/app/GenieWidget.apk proprietary/gapps
adb pull /system/app/Gmail.apk proprietary/gapps
adb pull /system/app/GoogleBackupTransport.apk proprietary/gapps
adb pull /system/app/GoogleCalendarSyncAdapter.apk proprietary/gapps
adb pull /system/app/GoogleContactsSyncAdapter.apk proprietary/gapps
adb pull /system/app/GoogleFeedback.apk proprietary/gapps
adb pull /system/app/GooglePartnerSetup.apk proprietary/gapps
adb pull /system/app/GoogleQuickSearchBox.apk proprietary/gapps
adb pull /system/app/GoogleServicesFramework.apk proprietary/gapps
adb pull /system/app/HtcCopyright.apk proprietary/gapps
adb pull /system/app/HtcEmailPolicy.apk proprietary/gapps
adb pull /system/app/HtcSettings.apk proprietary/gapps
adb pull /system/app/LatinImeGoogle.apk proprietary/gapps
adb pull /system/app/LatinImeTutorial.apk proprietary/gapps
adb pull /system/app/Maps.apk proprietary/gapps
adb pull /system/app/MarketUpdater.apk proprietary/gapps
adb pull /system/app/MediaUploader.apk proprietary/gapps
adb pull /system/app/NetworkLocation.apk proprietary/gapps
adb pull /system/app/OneTimeInitializer.apk proprietary/gapps
adb pull /system/app/PassionQuickOffice.apk proprietary/gapps
adb pull /system/app/SetupWizard.apk proprietary/gapps
adb pull /system/app/Street.apk proprietary/gapps
adb pull /system/app/Talk.apk proprietary/gapps
adb pull /system/app/Twitter.apk proprietary/gapps
adb pull /system/app/Vending.apk proprietary/gapps
adb pull /system/app/VoiceSearch.apk proprietary/gapps
adb pull /system/app/YouTube.apk proprietary/gapps
adb pull /system/app/googlevoice.apk proprietary/gapps
adb pull /system/app/kickback.apk proprietary/gapps
adb pull /system/app/soundback.apk proprietary/gapps
adb pull /system/app/talkback.apk proprietary/gapps
adb pull /system/etc/permissions/com.google.android.maps.xml proprietary/gapps
adb pull /system/etc/permissions/features.xml proprietary/gapps
adb pull /system/framework/com.google.android.maps.jar proprietary/gapps
adb pull /system/lib/libspeech.so proprietary/gapps

